### ISSUE TITLE
inkView.drawBitmap not working error NullPointerException

### ISSUE THREAD

**Issue by amir-ardalanuk** [simplifycom/ink-android#13]
i want to reDraw bitmap that i get from inkView.getBitmap but get error

**Comment by rubixhacker** [comment]
Can you please provide a stacktrace with the error?

**Comment by amir-ardalanuk** [comment]
` inkView.drawBitmap(temp.imgBitmap , temp.imgBitmap.getWidth() ,temp.imgBitmap.getHeight() , null); `

and error  : 

`FATAL EXCEPTION: main
                                                                                    Process: patinetdocument.trt.co.myapplication, PID: 2572
                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawBitmap(android.graphics.Bitmap, float, float, android.graphics.Paint)' on a null object reference
                                                                                        at com.simplify.ink.InkView.drawBitmap(InkView.java:417)
                                                                                        at patinetdocument.trt.co.myapplication.fragments.NewDocumentFragment.setTempBitmap(NewDocumentFragment.java:150)
                                                                                        at patinetdocument.trt.co.myapplication.fragments.NewDocumentFragment.onViewCreated(NewDocumentFragment.java:142)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1343)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1574)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
                                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
                                                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
                                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
                                                                                        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by nak5ive** [comment]
It looks like we have an internal reference that's not being initialized early enough.
We will work on a fix, but in the meantime, can you try clearing the ink view before your call to draw the bitmap?

```
inkView.clear();
inkView.drawBitmap(temp.imgBitmap , temp.imgBitmap.getWidth() ,temp.imgBitmap.getHeight() , null);
```

**Comment by amir-ardalanuk** [comment]
the first i want to thank for reply my message and your library ... is
amazing !
the second i tried that but get some error again from paint !

this is amir ardalan
android & ios Developer

**Comment by nak5ive** [comment]
Can you include whatever stacktrace you are seeing with your follow-up error?
In the sample app, I was able to execute this without error:
```
Bitmap tempBitmap = inkView.getBitmap();
inkView.clear();
inkView.drawBitmap(tempBitmap, 0, 0, null);
tempBitmap.recycle();
```

**Comment by amir-ardalanuk** [comment]
`java.lang.IllegalArgumentException: width and height must be > 0`

**Comment by amir-ardalanuk** [comment]
error in `inkView.class` and `clear` function in line 214 : 
`this.bitmap = Bitmap.createBitmap(this.getWidth(), this.getHeight(), Config.ARGB_8888);`

**Comment by holyman2k** [comment]
Hi, I run into the same problem, I have a image file taken on the camera, i can show it in the image view, when i try to draw on inkView, the app crashes, btw i'm using kotlin

`        val bitmap = BitmapFactory.decodeFile(filePath) 
        val width = bitmap.width.toFloat() 
        val height = bitmap.height.toFloat() 
        inkView.drawBitmap(bitmap, width, height, null)`

`FATAL EXCEPTION: main
                                                                      Process: com.omtrak.siteworks, PID: 25851
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.omtrak.siteworks/com.omtrak.siteworks.android.activities.AnnotationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawBitmap(android.graphics.Bitmap, float, float, android.graphics.Paint)' on a null object reference
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawBitmap(android.graphics.Bitmap, float, float, android.graphics.Paint)' on a null object reference
                                                                          at com.simplify.ink.InkView.drawBitmap(InkView.java:417)
                                                                          at com.omtrak.siteworks.android.activities.AnnotationActivity.onCreate(AnnotationActivity.kt:48)
                                                                          at android.app.Activity.performCreate(Activity.java:6221)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:172) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:145) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5832) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) `

**Comment by nak5ive** [comment]
how are you adding the ink view to your layout? is it inflated with the layout xml file, or are you programmatically adding it? Can you also try calling `inkView.clear();` before you attempt to draw the bitmap?

I was able to draw an image from Photos by modifying 2 files in the sample app. Can you test that the sample app works for you with the below modifications? (it just adds a photo menu item in the overflow menu)

### res/menu/options.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item
        android:id="@+id/menu_clear"
        android:title="@string/clear"
        android:icon="@drawable/ic_action_discard"
        app:showAsAction="ifRoom"/>
    <item
        android:id="@+id/menu_interpolation"
        android:title="@string/interpolation"
        android:checkable="true"
        app:showAsAction="never"/>
    <item
        android:id="@+id/menu_responsive"
        android:title="@string/responsive_weight"
        android:checkable="true"
        app:showAsAction="never"/>
    <item
        android:id="@+id/menu_photo"
        android:title="Photo"
        app:showAsAction="never"/>
</menu>
```

### MainActivity.java
```java
public class MainActivity extends Activity {

    private static final int RESULT_LOAD_IMG = 0;

    Toolbar toolbar;
    InkView inkView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        toolbar = (Toolbar) findViewById(R.id.toolbar);
        inkView = (InkView) findViewById(R.id.ink);

        initToolbar();
    }

    void initToolbar() {
        Menu menu = toolbar.getMenu();
        getMenuInflater().inflate(R.menu.options, menu);

        MenuItem item = menu.findItem(R.id.menu_interpolation);
        item.setChecked(inkView.hasFlag(InkView.FLAG_INTERPOLATION));
        item.setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
            @Override
            public boolean onMenuItemClick(MenuItem item) {
                item.setChecked(!item.isChecked());
                if (item.isChecked()) {
                    inkView.addFlag(InkView.FLAG_INTERPOLATION);
                } else {
                    inkView.removeFlag(InkView.FLAG_INTERPOLATION);
                }
                return true;
            }
        });

        item = menu.findItem(R.id.menu_responsive);
        item.setChecked(inkView.hasFlag(InkView.FLAG_RESPONSIVE_WIDTH));
        item.setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
            @Override
            public boolean onMenuItemClick(MenuItem item) {
                item.setChecked(!item.isChecked());
                if (item.isChecked()) {
                    inkView.addFlag(InkView.FLAG_RESPONSIVE_WIDTH);
                } else {
                    inkView.removeFlag(InkView.FLAG_RESPONSIVE_WIDTH);
                }
                return true;
            }
        });

        item = menu.findItem(R.id.menu_clear);
        item.setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM);
        item.setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
            @Override
            public boolean onMenuItemClick(MenuItem item) {
                inkView.clear();
                return true;
            }
        });

        item = menu.findItem(R.id.menu_photo);
        item.setOnMenuItemClickListener(new MenuItem.OnMenuItemClickListener() {
            @Override
            public boolean onMenuItemClick(MenuItem item) {
                Intent photoPickerIntent = new Intent(Intent.ACTION_PICK);
                photoPickerIntent.setType("image/*");
                startActivityForResult(photoPickerIntent, RESULT_LOAD_IMG);
                return true;
            }
        });
    }


    @Override
    protected void onActivityResult(int reqCode, int resultCode, Intent data) {
        super.onActivityResult(reqCode, resultCode, data);

        if (resultCode == RESULT_OK) {
            try {
                final Uri imageUri = data.getData();
                final InputStream imageStream = getContentResolver().openInputStream(imageUri);
                Bitmap selectedImage = BitmapFactory.decodeStream(imageStream);

                inkView.drawBitmap(selectedImage, 0, 0, null);

            } catch (FileNotFoundException e) {
                e.printStackTrace();
                Toast.makeText(MainActivity.this, "Something went wrong", Toast.LENGTH_LONG).show();
            }

        }else {
            Toast.makeText(MainActivity.this, "You haven't picked Image", Toast.LENGTH_LONG).show();
        }
    }
}
```

**Comment by JulesFrechette** [comment]
I seem to be having the same issue in a specific context: upon device orientation change.
I managed to avoid the errors mentioned above by calling 

> mInkView.drawBitmap(mBitmap, 0, 0, null);

in the **onInkClear()** method instead of calling in **onCreate()**.

Now even if I manage to call **drawBitmap()** with no errors, the bitmap is not being drawn. I cannot explain this as I previously saved my Bitmap in the **onSaveInstanceState()** method and confirmed it is not null before attempting to draw.

**Comment by dashika** [comment]
Hello, try this, in my case, it works)  
```

@Override
    public void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        byte[] bytes = savedInstanceState.getByteArray(EXTRA_SIGNATURE);
        bitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length);

        inkView.post( new Runnable() {
            @Override
            public void run() {
                if(bitmap!=null) {
                    inkView.clear();
                    inkView.drawBitmap(bitmap, 0, 0, null);
                }
            }
        });
    }
```
