### ISSUE TITLE
Firebase Crashlytics width and height must be > 0 v1.0.1

### ISSUE THREAD

**Issue by abhishekBansal** [simplifycom/ink-android#18]
I am receiving following crash report in Firebase Crashlytics

`Caused by java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
       at com.simplify.ink.InkView.clear(InkView.java:382)
       at myapp.MapsActivity.drawTapped(MapsActivity.java:3702)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
       at android.view.View.performClick(View.java:5623)
       at android.view.View$PerformClick.run(View.java:22433)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6316)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)`

This is happening for very small percentage of users. My app can change orientation. Any idea on why this might be happening?

**Comment by cren90** [comment]
I'm also seeing this with the following layout as a view item in a RecyclerView: 

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <TextView
        android:id="@+id/textCellBody"
        style="@style/FormBodyText"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/activity_vertical_margin_small"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constrainedWidth="true"
        app:layout_constraintTop_toTopOf="parent"
        tools:text="This is some text to prompt!" />

    <com.simplify.ink.InkView
        android:id="@+id/signature"
        android:layout_width="0dp"
        android:layout_height="150dp"
        android:layout_marginTop="@dimen/activity_vertical_margin_small"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        android:layout_marginEnd="@dimen/activity_horizontal_margin"
        android:layout_marginBottom="@dimen/activity_vertical_margin_small"
        app:inkFlags="interpolation|responsiveWeight"
        app:layout_constraintTop_toBottomOf="@id/textCellBody"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent" />

</android.support.constraint.ConstraintLayout>
```
